- name: install packages from loops
  hosts: local
  connection: local
  tasks:
  - name : "installing packages"
    ansible.builtin.package:
      name: "Installing {{ item }}"
      state: Installed
    loop:
    - gcc
    - nginx
    - git
    - zip
    - mysql

