- name: filters
  hosts: local 
  connection: local
  tasks:
  - name: handel undefine variables
    ansible.builtin.debug:
      msg: "Hello {{ person |default('Tulasi Annolla')}}"

  - name: convert string to list
    vars: 
      fruits: "apple,banana,orange"
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info : {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Coverting list to map  : {{ course | items2dict }}"

  - name: convert upper to lower
    vars:
      name: "Tulasi Annolla"
    ansible.builtin.debug:
      msg: "convert to lower: {{ name | lower }}"
    
  - name: Convert to upper
    vars:
      name: "Tulasi Annolla"
    ansible.builtin.debug:
      msg: "Convert to upper : {{ name | upper }}"

  
  - name : find min and max
    vars:
      numbers: [3,6,9,2345]
    ansible.builtin.debug:
      msg: "min is :{{ numbers | min }} , max is {{ numbers | max }}"

  - name: check ip address is valid or ot
    vars:
      ip: "2345:657:76:90"
    ansible.builtin.debug:
      msg: "check whether the ip is valid or not: {{ ip | ansible.utils.ipaddr }}"