- name: filters
  hosts: local 
  connection: local
  tasks:
  - name: handel undefine variables
    ansible.builtin.debug:
      msg: "Hello {{ person |default('Tulasi Annolla')}}"

  - name: convert string to list
    vars: 
      fruits: "apple,banana,orange"
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info : {{ course | dict2items }}"